mp_platform_home:
    path:    /{page}
    defaults:  { _controller: MPPlatformBundle:Advert:index, page: 1 }
    requirements: 
        page: '\d+'
    
mp_platform_view:
    path:    /advert/{id}
    defaults:  { _controller: MPPlatformBundle:Advert:view }


mp_platform_edit:
    path:    /edit/{id}
    defaults:  { _controller: MPPlatformBundle:Advert:edit }
    requirements: 
        id: '\d+'
        
mp_platform_delete:
    path:    /delete/{id}
    defaults:  { _controller: MPPlatformBundle:Advert:delete }
    requirements: 
        id: '\d+'
    
mp_platform_add:
    path:    /add
    defaults:  { _controller: MPPlatformBundle:Advert:add }
    

mp_platform_recherche:
    path:    /recherche
    defaults:  { _controller: MPPlatformBundle:Advert:recherche }

mp_platform_map:
    path:    /map/{id}
    defaults:  { _controller: MPPlatformBundle:Advert:map }

mp_platform_favoris:
    path:    /favoris/{id}
    defaults:  { _controller: MPPlatformBundle:Advert:favoris }
    requirements: 
        id: '\d+'


